<?php
/**
 * @file
 * Ding - toggle short/long format
 */

/**
 * Implements hook_block_info().
 */
function ding_toggle_format_block_info() {
  return array(
    'toggle' => array(
      'info' => t('Ding format toggle'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function ding_toggle_format_block_view($delta = '') {

  drupal_add_js(drupal_get_path('module', 'ding_toggle_format') . '/js/ding_toggle_format.js');
  drupal_add_js(drupal_get_path('module', 'ding_toggle_format') . '/js/jquery.cookie.min.js');

  drupal_add_css(drupal_get_path('module', 'ding_toggle_format') . '/css/ding_toggle_format.css');

  return array(
    'subject' => t('Ding toggle format'),
    'content' => ding_toggle_format_render_link(),
  );
}

/**
 * Return rendered image link to toggle format, and label.
 */
function ding_toggle_format_render_link() {
  // Construct the image's path (.gif stored in a module sub-dir).
  $image_path = drupal_get_path('module', 'ding_toggle_format') . '/images/blank.gif';

  // Make some text for the image's alt & title tags (SEO, accessibility).
  $image_alt = t('Toggle format');
  $image_title = t('Toggle format link');
  $format_prefix = '<span class="ding-toggle-format-label">' . t('Display format:') . '</span>';

  // Render image html using theme_image (returns NULL if file doesn't exist).
  $format_image = theme('image', array(
    'path' => $image_path,
    'alt' => $image_alt,
    'title' => $image_title,
    'attributes' => array(
      'id' => 'ding-toggle-format-image',
    ),
  ));

  // If the image rendered ok, render link using above variables.
  $format_link = array();
  if ($format_image) {
    $format_link = $format_prefix . l($format_image, '#', array(
      'html' => TRUE,
      'attributes' => array(
        'title' => $image_title,
        'id' => 'ding-toggle-format',
        'class' => 'ding-toggle-format-short',
      ),
    ));
  }

  return $format_link;
}

/**
 * Implements hook_preprocess().
 */
function ding_toggle_format_preprocess(&$variables, $hook) {
  $search_result = arg(0) == 'search' && arg(1) == 'ting';
  $user_page = arg(0) == 'user' && arg(2) == 'status';

  // Force toggle format being inserted to search result and
  // user pages.
  if (!$search_result && !$user_page) {
    return;
  }

  if ($hook == '25_50_25') {
    $block = module_invoke('ding_toggle_format', 'block_view', '');
    $toggle_format_markup =
      '<div class="panel-pane pane-block pane-ding-toggle-format-toggle">' .
      '<div class="pane-content">' .
      render($block['content']) .
      '</div>' .
      '</div>';

    $existing_content = $variables['content']['main_content'];
    $variables['content']['main_content'] = $toggle_format_markup . $existing_content;
  }
}
